version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.2
    - 3.11.0
    - 3.9.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: element-ui
    versions:
    - 2.15.1
